### ISSUE TITLE
Jar files in libs folder of in AAR package was not picked up

### ISSUE THREAD

**Issue by jianinz** [simpligility/android-maven-plugin#484]
Hi guys, 

Today when i bumped maven-plugin version to 4.0.0-rc.1, android API version to 21, support-v4 library to 21, i am having exception when switching fragment.

``` java
0-21 12:57:28.359    1745-1745/com.izettle.android E/dalvikvm﹕ Could not find class 'android.support.v4.app.FragmentTransitionCompat21$EpicenterView', referenced from method android.support.v4.app.BackStackRecord$TransitionState.<init>
10-21 12:57:28.359    1745-1745/com.izettle.android W/dalvikvm﹕ VFY: unable to resolve new-instance 310 (Landroid/support/v4/app/FragmentTransitionCompat21$EpicenterView;) in Landroid/support/v4/app/BackStackRecord$TransitionState;
10-21 12:57:28.359    1745-1745/com.izettle.android D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0013
10-21 12:57:28.359    1745-1745/com.izettle.android D/dalvikvm﹕ DexOpt: unable to opt direct call 0x0632 at 0x15 in Landroid/support/v4/app/BackStackRecord$TransitionState;.<init>
10-21 12:57:28.359    1745-1745/com.izettle.android D/AndroidRuntime﹕ Shutting down VM
10-21 12:57:28.359    1745-1745/com.izettle.android W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xa4c0d648)
10-21 12:57:28.399    1745-1745/com.izettle.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: android.support.v4.app.FragmentTransitionCompat21$EpicenterView
            at android.support.v4.app.BackStackRecord$TransitionState.<init>(BackStackRecord.java:1456)
            at android.support.v4.app.BackStackRecord.beginTransition(BackStackRecord.java:1018)
            at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:883)
            at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1541)
            at android.support.v4.app.FragmentManagerImpl$2.run(FragmentManager.java:493)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```
1. I am using Intellij which has gen-external-libs holds the aar dependency
2. the actual class `FragmentTransitionCompat21` resides in `libs/internal_impl-21.0.0.jar` but the caller resides in `classes.jar`

I am wondering does it have something to do with maven plugin? It looks like APK doesn't pacakge `libs/internal_impl-21.0.0.jar`?

Thanks!

**Comment by denniskorir** [comment]
I am using Xamarin and experiencing the same problem

**Comment by mosabua** [comment]
Same applies to you @denniskorir .. please file a new issue following http://simpligility.github.io/android-maven-plugin/report-issue.html
